# Generated by Django 4.1.3 on 2022-11-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Newsflash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("newsid", models.IntegerField()),
                ("Name", models.CharField(max_length=1000)),
                ("Desc", models.CharField(max_length=10000)),
            ],
        ),
    ]
