# Generated by Django 4.1.3 on 2022-11-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NDTVapp", "0002_story"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topstory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("newsid", models.CharField(max_length=500)),
                ("Name", models.CharField(max_length=1000)),
                ("Desc", models.CharField(max_length=10000)),
                ("image", models.ImageField(blank=True, upload_to="images")),
            ],
        ),
    ]
