# Generated by Django 4.1.3 on 2022-11-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NDTVapp", "0003_topstory"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Videoid", models.CharField(max_length=500)),
                ("caption", models.CharField(max_length=200)),
                ("video", models.FileField(upload_to="Video")),
            ],
        ),
    ]
